### ISSUE TITLE
请问这是仓颉SDK哪个版本？

### ISSUE THREAD

**Issue by xflcx1991** [Zxilly/playground-cj#3]
如题，最近仓颉SDK一个月已更新，线上的是哪个版本呢？

**Comment by Zxilly** [comment]
是最新的 0.54.3

https://github.com/Zxilly/playground-cj/blob/2d4761f87feddc272c349ad73b82641f7c391561/codapi/Dockerfile#L10

**Comment by SmiteWindows** [comment]
在网页上显示,最好

**Comment by xflcx1991** [comment]
> 是最新的 0.54.3
> 
> https://github.com/Zxilly/playground-cj/blob/2d4761f87feddc272c349ad73b82641f7c391561/codapi/Dockerfile#L10

感谢
